import { StyleSheet } from 'react-native';
import { colors } from 'src/shared/ui/theme/colors';

const CARD_WIDTH = 200;
const CARD_HEIGHT = 300;
const PHOTO_SIZE = 190;

const styles = StyleSheet.create({
  cardShadow: {
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    borderRadius: 32,
    marginHorizontal: 12,
    marginBottom: 12,
    backgroundColor: 'transparent',
  },
  card: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    borderRadius: 32,
    backgroundColor: colors.white,
    alignItems: 'flex-start',
    paddingTop: 20,
    paddingBottom: 18,
    paddingHorizontal: 20,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'flex-start',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    width: '100%',
  },
  logoBox: {
    width: 40,
    height: 40,
    marginRight: 10,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    overflow: 'hidden',
  },
  logoBorder: {
    borderWidth: 1.5,
    borderColor: colors.textSecondary,
    borderRadius: 12,
    borderStyle: 'dashed',
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  clubLogo: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
  },
  clubName: {
    fontSize: 18,
    color: colors.warning,
    fontWeight: '700',
    letterSpacing: 1.2,
    marginLeft: 2,
    flex: 1,
    textShadowColor: colors.grayDark,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 2,
  },
  photoWrapper: {
    position: 'absolute',
    right: -50,
    top: 48,
    width: PHOTO_SIZE,
    height: PHOTO_SIZE + 10,
    zIndex: 2,
    borderRadius: 32,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  playerPhoto: {
    width: PHOTO_SIZE,
    height: PHOTO_SIZE + 10,
    resizeMode: 'cover',
    borderRadius: 32,
    backgroundColor: 'transparent',
  },
  nameBlock: {
    marginTop: 50,
    position:'absolute',
    bottom:20,
    left:20,
    alignItems: 'flex-start',
    zIndex: 3,
  },
  playerName: {
    fontSize: 26,
    fontWeight: 'bold',
    lineHeight: 32,
    height: 32,
    letterSpacing: 0.5,
    textAlign: 'left',
    color: colors.grayDark,
    textShadowColor: colors.text,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },
  shirtNumber: {
    fontSize: 14,
    color: colors.gradientEnd,
    fontWeight: '400',
    marginTop: 10,
    marginLeft: 2,
    alignSelf: 'flex-start',
    fontFamily: 'Oswald-Bold',
    textShadowColor: colors.warning,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },
});

export default styles; 